[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./chainlink-functions" }]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "chainlink/=lib/chainlink/",
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

# Network configurations
[rpc_endpoints]
fuji = "${AVALANCHE_FUJI_RPC}"
avalanche = "${AVLANACHE_MAINET_RPC}"

# Verification configuration for Snowtrace
[etherscan]
fuji = { key = "${AVALANCHE_FUJI_ETHERSCAN_API_KEY}", url = "https://api-testnet.snowtrace.io/api", chain = 43113 }
avalanche = { key = "${AVALANCHE_MAINNET_ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api", chain = 43114 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
